- name: Run Database Container
  docker_container:
    name: my-db
    image: fapo030/tp-devops-database:latest
    recreate: true
    networks: 
     - name: network_one
    env:
      POSTGRES_DB: "db" 
      POSTGRES_USER: "usr"
      # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
      POSTGRES_PASSWORD: "pwd"