version: '3.7'

services:
  backend:
    build: ./backend_api
    container_name: my-api
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    container_name: my-db
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  httpd:
    build: ./httpserver
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

volumes:
  db-volume:

networks:
  my-network: